categories = {
  Housing: "🏠",
  Gift: "🎁",
  Others: "🎃",
  Dining: "🍽",
  Transportation: "🚌",
  Grocery: "🧻",
  Game: "🎮",
  Clothing: "👗",
  Travel: "✈️",
  Hotel: "🏨",
  Pet: "🐶",
  Transfer: "💸",
  Study: "💡",
  Meidical: "🏥",
  Creative: "🤯",
};
